package com.ivandroid.foro_hub_alura.domain.curso;

public enum Categoria {
    PROGRAMACION,
    DESARROLLO_WEB,
    DESARROLLO_MOVIL,
    CIENCIA_DE_DATOS,
    INTELIGENCIA_ARTIFICIAL,
    CIBERSEGURIDAD,
    DEVOPS,
    BASES_DE_DATOS,
    REDES,
    SISTEMAS_OPERATIVOS,
    ARQUITECTURA_DE_SOFTWARE,
    TESTING,
    BIG_DATA,
    INTERNET_DE_LAS_COSAS,
    BLOCKCHAIN,
    REALIDAD_VIRTUAL,
    REALIDAD_AUMENTADA,
    ROBOTICA,
    MACHINE_LEARNING
}
